name: Compile gh-to-tg-bot to EXE

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Also trigger on PRs to the main branch

jobs:
  build:
    runs-on: windows-latest  # Run on a Windows machine (GitHub-hosted runner)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies from requirements.txt
        pip install pyinstaller  # Install PyInstaller to build the .exe file

    - name: Build the .exe file with PyInstaller
      run: |
        pyinstaller --onefile --distpath dist --workpath build gh-to-tg-bot.py  # Build the .exe file using PyInstaller

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: gh-to-tg-bot-exe
        path: dist/gh-to-tg-bot.exe  # Upload the .exe file generated in the dist folder
